language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
notifications:
  email:
    - thomas.vandoren@gmail.com
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.13
matrix:
  allow_failures:
    - env: PUPPET_VERSION=2.6.14
