name         'thomasvandoren-innotop'
version      '0.0.1'
author       'Thomas Van Doren'
summary      'innotop 1.8.1'
description  'Install innotop 1.8.1 from tarball.'
license      'GPLv2'
project_page 'https://github.com/thomasvandoren/puppet-innotop'
